version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

services:
  toposoid-deduction-unit-sentence-vector-match-web:
    image: toposoid/toposoid-deduction-unit-sentence-vector-match-web:0.4
    environment:
      - GRAPHDB_HOST=172.30.0.2
      - PRIVATE_IP_ADDRESS=localhost
      - SCALA_DATA_ACCESSOR_NEO4J_WEB_HOST=172.30.0.3
      - COMMON_NLP_JP_WEB_HOST=172.30.0.5
      - COMMON_NLP_EN_WEB_HOST=172.30.0.7
      - TOPOSOID_VALD_ACCESSOR_HOST=172.30.0.9
      - TOPOSOID_VALD_SEARCH_NUM_MAX=5
      - PLAY_HTTP_PORT=9103
    networks:
      app_net:
        ipv4_address: 172.30.0.4
    ports:
      - 9103:9103
    depends_on:
      - neo4j
      - data-accessor-vald-web
      - toposoid-common-nlp-japanese-web
      - toposoid-common-nlp-english-web
  toposoid-common-nlp-japanese-web:
    image: toposoid/toposoid-common-nlp-japanese-web:0.4
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.5
      - SYNONYM_NOUN_SIMILARITY_THRESHHOLD_JP=0.52
      - SYNONYM_VERB_SIMILARITY_THRESHHOLD_JP=0.52
      - WORD2VEC_SIMILARITY_THRESHHOLD_JP=0.68
      - CHIVE_MODEL_VERSION=chive-1.2-mc15.kv
      - TOPOSOID_SENTENCEBERT_MODEL_JP=sentence-transformers/paraphrase-multilingual-mpnet-base-v2
      - PLAY_HTTP_PORT=9006
    networks:
      app_net:
        ipv4_address: 172.30.0.5
    ports:
      - 9006:9006
  toposoid-common-nlp-english-web:
    image: toposoid/toposoid-common-nlp-english-web:0.4
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.7
      - SYNONYM_NOUN_SIMILARITY_THRESHHOLD_EN=0.52
      - SYNONYM_VERB_SIMILARITY_THRESHHOLD_EN=0.52
      - WORD2VEC_SIMILARITY_THRESHHOLD_EN=0.78
      - TOPOSOID_SENTENCEBERT_MODEL_EN=sentence-transformers/paraphrase-multilingual-mpnet-base-v2
      - PLAY_HTTP_PORT=9008
    networks:
      app_net:
        ipv4_address: 172.30.0.7
    ports:
      - 9008:9008
  scala-data-accessor-neo4j-web:
    image: toposoid/scala-data-accessor-neo4j-web:0.4
    environment:
      - GRAPHDB_HOST=172.30.0.2
      - PRIVATE_IP_ADDRESS=172.30.0.3
      - PLAY_HTTP_PORT=9005
    networks:
      app_net:
        ipv4_address: 172.30.0.3
    ports:
      - 9005:9005
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:4.1.3
    environment:
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_AUTH=neo4j/p@ssw0rd
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      app_net:
        ipv4_address: 172.30.0.2
  data-accessor-vald-web:
    image: toposoid/data-accessor-vald-web:0.4
    environment:
      - TOPOSOID_VALD_HOST=172.30.0.10
      - TOPOSOID_VALD_PORT=8081
      - TOPOSOID_VALD_DISTANCE_THRESHHOLD=0.25 #For Multilingual Model 0.03
    networks:
      app_net:
        ipv4_address: 172.30.0.9
    ports:
      - 9010:9010
    depends_on:
      - vald
  vald:
    image: vdaas/vald-agent-ngt:v1.6.3
    user: 1000:1000
    volumes:
      - ./vald-config:/etc/server
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    networks:
      app_net:
        ipv4_address: 172.30.0.10
    ports:
      - 8081:8081




